### PR TITLE
Upgrade to rustc 1.70.0

### PR DESCRIPTION
**Pull request by Dawn-githup**

### CODE REVIEW

**Comment by ashuralyk** [comment]
the latest cargo version is 1.74.0, why do we only upgrade to 1.70.0?

**Comment by Dawn-githup** [comment]
> the latest cargo version is 1.74.0, why do we only upgrade to 1.70.0?

When I was in Install Cross, I was prompted to upgrade to version 1.70.0 or above, so I chose 1.70.0.
Do we need to upgrade to the latest version?

**Comment by ashuralyk** [comment]
> > the latest cargo version is 1.74.0, why do we only upgrade to 1.70.0?
> 
> When I was in Install Cross, I was prompted to upgrade to version 1.70.0 or above, so I chose 1.70.0. Do we need to upgrade to the latest version?

I encountered an error in compiling if I switch it to 1.70.0 while executing `capsule build`

**Comment by ashuralyk** [comment]
I think this change is ok after using OrdStack in my PC

**Review by ashuralyk — APPROVED** [review]

**Pull request merged**
