### PR TITLE
feat!: combine multiple error files into one crate and solve bugs

### LINKED ISSUE #15: Logic conflict in payment related contracts
## Description

We discovered that the current version of the spore-contract has some logic issues when involving payment process:
- Incorrect payment amount required when:
    - creating multiple Spores/ClusterAgents in the same transaction
    - each Spore/ClusterAgent requires one or more payments to the same lock hash
- Incorrect payment amount required when:
    - creating a Spore that references multiple Mutants
    - each Mutant requires a payment to the same lock hash

Ref: 
- https://github.com/sporeprotocol/spore-contract/blob/master/contracts/spore/src/entry.rs#L210-L225
- https://github.com/sporeprotocol/spore-contract/blob/master/contracts/cluster_agent/src/entry.rs#L51-L67

### Creating a Spore that references multiple Mutants

Take an example, say A has 2 Mutants:
- Mutant 1, minPayment = 10
- Mutant 2, minPayment = 11

And B tries to create a Spore, which has the following contentType:
```
text/plain;mutant[]="mutant1,mutant2"
```

Generally, B should pay A:
```
payment_for_mutant_1 = 10^10 shannons = 100 CKB
payment_for_mutant_2 = 10^11 shannons = 1000 CKB
payment = sum(payment_for_mutant_1, payment_for_mutant_2) = 1100 CKB
```

But in the curernt version of the contract, each Mutant's payment will be calculated individually:
```
Outputs:
  - Spore
    - Mutant 1: I need A to gain 100 CKB from the transaction, I don't care the rest
    - Mutant 2: I need A to gain 1000 CKB from the transaction, I don't care the rest
```

So, B should pay A:
```
payment_for_mutant_1 = 10^10 shannons = 100 CKB
payment_for_mutant_2 = 10^11 shannons = 1000 CKB
payment = max(payment_for_mutant_1, payment_for_mutant_2) = 1000 CKB
```

### Creating multiple ClusterAgents in the same transaction

Take an example, say A has a ClusterProxy:
- ClusterProxy 1, minPayment = 10

And B tries to create 2 ClusterAgents in one transaction:
- ClusterAgent 1, references ClusterProxy 1
- ClusterAgent 2, references ClusterProxy 1

Generally, in the transaction, B should pay A:
```
payment_for_agent_1 = 10^10 shannons = 100 CKB
payment_for_agent_2 = 10^10 shannons = 100 CKB
total_payment = sum(payment_for_agent_1, payment_for_agent_2) = 200 CKB
```

But in the current version, each ClusterAgent runs its own payment checks:
```
Outputs:
  - ClusterAgent 1: I need A to gain 100 CKB from the transaction, I don't care the rest
  - ClusterAgent 2: I need A to gain 100 CKB from the transaction, I don't care the rest
```

So, B should pay A:
```
payment_for_agent_1 = 10^10 shannons = 100 CKB
payment_for_agent_2 = 10^10 shannons = 100 CKB
total_payment = max(payment_for_agent_1, payment_for_agent_2) = 100 CKB
```

### LINKED ISSUE #17: InvalidLuaScript error when creating a Mutant
I was trying to create a Mutant with the example code (slightly modified) in [MUTANT.md](https://github.com/sporeprotocol/spore-contract/blob/master/MUTANT.md), but got an error code 11 ([InvalidLuaScript](https://github.com/sporeprotocol/spore-contract/blob/80df6166ef99b0d69cda326b5d07b4bfeadf9b5c/contracts/spore_extension_lua/src/error.rs#L17)):

```lua
if spore_output_index > 0 then
  ckb.exit_script(88)
end
```

The Mutant output in my transaction:
```json
{
  "capacity": "0x44eaf9900",
  "lock": {
    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
    "hash_type": "type",
    "args": "0xe390d4b9b4c7637ec80799bdaf644ae625cdb922"
  },
  "type": {
    "code_hash": "0xb4d3f207831e2774d310a87571fb0095f5b4af4fa176d8bfaae0191a4d6989c8",
    "hash_type": "data1",
    "args": "0x8477693d6d030f2eb33cfdace798d79ce46bcd602de1895f0e3f2afe706c0b820a"
  }
}
```

### LINKED ISSUE #18: A condition issue when transferring a Mutant
The following code block suggets that when transferring a Mutant cell, if `input_data == output_data`, the script should ends with a [ModifyPermanentField](https://github.com/sporeprotocol/spore-contract/blob/80df6166ef99b0d69cda326b5d07b4bfeadf9b5c/contracts/spore_extension_lua/src/error.rs#L11C14-L11C14) error. However, it appears that the condition check does not match the error's description.

Ref:
https://github.com/sporeprotocol/spore-contract/blob/80df6166ef99b0d69cda326b5d07b4bfeadf9b5c/contracts/spore_extension_lua/src/entry.rs#L108-L110

### LINKED ISSUE #19: Unknown error when creating a Spore (applying a Mutant)
### Description

I created a Mutant and attempted to create a Spore to apply the Mutant, but encountered an error 100 ([Unknown](https://github.com/sporeprotocol/spore-contract/blob/80df6166ef99b0d69cda326b5d07b4bfeadf9b5c/contracts/spore/src/error.rs#L25)).

Based on this error, I can identify two issues:
- The error 100 (Unknown) is unclear. Is it possible to throw the exact error code from `lua-vm` or `ckb.exit_script(code)` to provide more specific information?
- The lua code contained in the Mutant seems to be capable of functioning correctly, I am unsure why it failed. Is it possible that something went wrong in the Mutant contract itself? Or can anyone help review the lua code?

### More info

The Mutant's lua code:
```lua
if spore_ext_mode == 2 then
  ckb.exit_script(10086)
end
```

The Mutant's OutPoint (view on [Explorer](https://pudge.explorer.nervos.org/transaction/0xf4354a508d130a2d28db03654c37cef8eb67a8cd0defe830f01af2bb1a5fa5fd)):
```json
{
  "tx_hash": "0xf4354a508d130a2d28db03654c37cef8eb67a8cd0defe830f01af2bb1a5fa5fd",
  "index": "0x0"
}
```

The new Sproe's output (from the transaction that failed):
```json
{
  "capacity": "0x5ae5a7400",
  "lock": {
    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
    "hash_type": "type",
    "args": "0x6cd8ae51f91bacd7910126f880138b30ac5d3015"
  },
  "type": {
    "code_hash": "0xd0d46552fc27b489425bb8f72ea9a371df49c978b27e1e7e8bffe6f9c72560c6",
    "hash_type": "data1",
    "args": "0x1a4482480b9f0ac92d59e4cdcf9fa6d153bf82bc45906dc1b6498ed1485db6e4"
  }
}
```

### LINKED ISSUE #21: Using `build.rs` to automatically generate hardcoded `code_hash` constant parameter for contracts
Spore contracts need to check their binary hashes to ensure the right cooperator that interacts with, so some contracts should hardcode their cooperator's binary hash, but this leads inconvenience for testing

### PR DESCRIPTION
**Pull request by ashuralyk**
# Description
while testing Spore contracts in `spore-sdk` we found few bugs that have to solve and some process that can optimize

the thing that should be clarified is, the returned error code from Lua should be limited in range [\[-127, 0)](https://github.com/sporeprotocol/spore-contract/pull/20/files#diff-8d549c2d1ba673519521ed7b5e76b8afda7302b4e691fc56a0927b30593d6015R97)

all warnings have been killed including test cases

p.s. some changes are from my editor formatter

# Tasks list
- [x] close #17 
- [x] close #18 
- [x] close #19 
- [x] close #21 

# Appendix

contracts also have potential bugs after solving recorded bugs in above tasks list, all of new bugs are recorded right in this PR's comment section

### CODE REVIEW

**Comment by ashuralyk** [comment]
@RongxinZhang now we can directly follow steps in README.md to build and test

**Comment by ashuralyk** [comment]
@ShookLyngs I'm not sure wether issue #19 has been solved, because I guess it's an error handling problem that I've already put work on it in this PR

**Comment by ShookLyngs** [comment]
> @ShookLyngs I'm not sure wether issue #19 has been solved, because I guess it's an error handling problem that I've already put work on it in this PR

Will continue test on them with the sdk.
And by "error handling problem" do you mean I should restric the error code in my lua code in range [-127, 0)? 

By the way:
- Do you think we should get more reviewers on the code? I can only read part of the code.
- Do you think we can have testnet deployments for sdk testing?

**Comment by ashuralyk** [comment]
@ShookLyngs 
> restrict error code in Lua 
yes

> get more reviewers
yes, but a little difficult for now @RongxinZhang 

> deployment on testate
yes, refer to here https://github.com/sporeprotocol/spore-contract/pull/22/files

**Comment by ShookLyngs** [comment]
https://github.com/nervosnetwork/ckb-lua-vm/blob/ab2045a2e1bb3d18f159db609572b4ec97784dfb/docs/dylib.md#lua_run_code
> Lua script should pass non-negative number to ckb.exit_script in order to distinguish lua interpreter error and delibrately set return code.

It seems that negative error codes are not supposed be passed to the `ckb.exit_script`?

**Comment by ShookLyngs** [comment]
> I encountered an error with a code of -2 when attempting to create a Mutant.

Update: I created a Mutant using another lua code. This time I didn't use the `spore_output_index` variable, so perhaps you can check if it was an injection issue. 

Here's the lua code I used, which worked:
```lua
if spore_ext_mode == 2 then
  ckb.exit_script(86)
end
```

---

Another problem I encountered was when I attemped to create a Spore with a Mutant, a `57` error was returned. If I'm correct, it's the [MutantIDNotValid](https://github.com/sporeprotocol/spore-contract/pull/20/files#diff-a18bc78774ba5f01acf376a5f7d930dfb0f2ce215fe5b961425e54ef02932454R71) error, correct me if I'm wrong. 

I Looked at the contract, here's where the error is thrown: https://github.com/sporeprotocol/spore-contract/blob/80df6166ef99b0d69cda326b5d07b4bfeadf9b5c/lib/utils/src/mime.rs#L89-L92

I don't fully understand rust, but if the quoted code block is attempting to check the length of a hex hash, maybe the expected length should be 66 (including the "0x") instead of 32? 

An example of a mime with Mutant Ids specified:
```
text/plain;mutant[]=0x193ce52621a22a354efd4f4d98c7e7b7f8cff30cc1fd4b9d8a88c2558cf4a5b4
```

---

And by the way, it's a bit challenging to search for a specific error code because most of the error codes are auto generated within enum. Do you think since the error codes are combined together, is it better to specify each error's code for better querying?

Ref: https://github.com/sporeprotocol/spore-contract/blob/1a1415acefc40e805761d2869142480bad23541e/lib/errors/src/error.rs

**Comment by ashuralyk** [comment]
> Do you think since the error codes are combined together, is it better to specify each error's code for better querying?

most of error code from different contracts in previous pattern share a same range, so combining them into one enum could be better to distinguish them, because all of error codes are unique

**Comment by ashuralyk** [comment]
@ShookLyngs I find your creation of mutant cell is dispatched to a particular process in `spore_extension_lua` contract that doesn't inject `spore_ext_mode` and `spore_output_index` variables, it's happened when the mutant cell is put in transaction's output field

I adjusted it in the latest commit, here is its new logic:
1. `spore_ext_mode = 0 (nil for previous)` => creation of mutant cell called in `output` field
2. `spore_ext_mode = 1 (0 for previous)` => creation of mutant cell called in `celldep` field
3. `spore_ext_mode = 2 (1 for previous)` => transfer of mutant cell called in `celldep` field
4. `spore_ext_mode = 3 (2 for previous)` => destroy of mutant cell called in `celldep` field

**Comment by ShookLyngs** [comment]
> most of error code from different contracts in previous pattern share a same range, so combining them into one enum could be better to distinguish them, because all of error codes are unique

Yeah, I'm not against the idea. It's just difficult to find an error by its error code.
So I mean maybe the error codes should be declared more explicitly. 

For example, maybe declare them like this:
```js
// common
ClusterCellNotInDep = 10,
ClusterOwnershipVerifyFailed,

// spore_extension_lua errors
ModifyExtensionPermanentField = 12,
ConflictExtensionCreation,
...

// cluster_proxy errors
InvalidProxyOperation = 23,
ImmutableProxyFieldModification,
...
```

Instead of this:
```js
// common
ClusterCellNotInDep = 10,
ClusterOwnershipVerifyFailed,

// spore_extension_lua errors
ModifyExtensionPermanentField,
ConflictExtensionCreation,
...

// cluster_proxy errors
InvalidProxyOperation,
ImmutableProxyFieldModification,
...
```

**Comment by ashuralyk** [comment]
> So I mean maybe the error codes should be declared more explicitly

I've thought of this but didn't do, if you say so, it's a good change

> This way, people wouldn't have to search for errors in the source code

Good idea, but I don't understand all of these error codes meaning, so I'll mark it

**Comment by ashuralyk** [comment]
@ShookLyngs new changes have applied to PR #22 already (rebased and force-push), please take them and start the test again

**Comment by ShookLyngs** [comment]
Update:

1. #17 
    
    Succesfully created a Mutant with `spore_ext_mode` and `spore_output_index` referenced in the code.
    However, not sure what would be the value of `spore_output_index` be when `spore_ext_mode == 0`.
    
    The lua code I used:
    ```lua
    if spore_ext_mode == 1 and spore_output_index > 0 then
      ckb.exit_script(88)
    end
    ```

2. #18 
    
    Transferred a Mutant: `0x215dc252e2724ad535c3ed1fb3817893d032db941f174dbda72e693122987c4e`.
    No problem with it.
    
3. #19 

    - The Unkonwn error was gone.
    - The 57 (MutantIDNotValid) error was gone.
    - A new 49 (ExtensionCellNotInDep) error was occured when attempted to create a Spore with a Mutant.

    I suppose it means that the required Mutant was not in cellDeps. However, I have already included the referenced Mutant in cellDeps. Can you take a look at it?
    
    Ref: https://github.com/sporeprotocol/spore-contract/blob/80df6166ef99b0d69cda326b5d07b4bfeadf9b5c/contracts/spore/src/entry.rs#L163-L175

**Comment by ashuralyk** [comment]
> A new 49 (ExtensionCellNotInDep) error was occured when attempted to create a Spore with a Mutant.

confirmed, and now I feel like it's fixed, I'll provide deployment information later

**Comment by ShookLyngs** [comment]
Update: 

An `14` (InvalidExtensionID) error occured when attempting to create a Mutant cell.
I guess it's because Mutant type args has 33 bytes: `<32-byte type-id><1-byte min-payment>`.

Info:

- Mutant type code hash: `0x494ba9e4a52462be761cc6e9660ee999981317e8240dad29002c05a56a944504`

- Mutant Id: `0x87a5bad1849ba09237bdd62209b538c3f39b27ba6dceefd040d5f9f71f6adfb5`

- Transaction.inputs[0]:
  ```json
  {
    "previous_output": {
      "tx_hash": "0xcb7c6e7a3cc199523abec9fdc9e1168cff7f73a362b531fc6241125a01d9b80d",
      "index": "0x1"
    },
    "since": "0x0"
  }
  ```

- Mutant output index: `0x0`

**Comment by ashuralyk** [comment]
@ShookLyngs 
> An 14 (InvalidExtensionID) error was occured when attempting to create a Mutant cell.

this issue has been solved, and I merged `chore/deployment` branch to the branch in of this PR, so the deployment information can directly find in here

**Comment by ashuralyk** [comment]
@ShookLyngs if other features except Mutant are fine, I think this PR can be merged, please take your time to have a check

**Comment by ShookLyngs** [comment]
Update:

Sorry, I was busy listing everything that needed to be tested, just in case something was skipped.

Now that I've tested everything I could (except for Mutant-related features), and most features are functioning normally as expected, there is still one issue we may need to resolve: Spore V2 doesn't currently support referencing Cluster V2.

The original design was to allow newer versions of Spores to reference older versions of Clusters. For example, a Spore V2 should be able to reference a Cluster V1. However, in the current version of Spore V2 (0x49d12...), when I attempted to create a Spore V2 and referenced a Cluster V1 (0x598d7...) in the transaction, a `5` (ClusterCellNotInDep) error occurred.

Cluster V1 testnet info:
```json
{
  "code_hash": "0x1dbd4b03f1cf9d27b5359f8e3569efcb848bc71e6f204654509ce67c07bb1fdd",
  "tx_hash": "0x91555ebd2bbddf80da141a58220648d6dd3f8c04ba4bb8312d01907165b636ad",
  "index": "0x0"
}
```

**Comment by ashuralyk** [comment]
> Spore V2 doesn't currently support referencing Cluster V1

I injected older version `code_hash` of Cluster in Spore and Cluster_proxy contracts, but I found older Cluster code hash is not the one you listed, I used this one mentioned in README.md:

image

**Comment by ShookLyngs** [comment]
> but I found older Cluster code hash is not the one you listed

You're right, this is the correct one, matching your info:
```json
{
  "code_hash": "0x598d793defef36e2eeba54a9b45130e4ca92822e1d193671f490950c3b856080",
  "tx_hash": "0x49551a20dfe39231e7db49431d26c9c08ceec96a29024eef3acc936deeb2ca76",
  "index": "0x0"
}
```

**Review by ShookLyngs — APPROVED** [review]

**Pull request merged**
